### ISSUE TITLE
More fields in a single course

### ISSUE THREAD

**Issue by jysim3** [StevenShen1999/projectTauCeti#3]
![image](https://user-images.githubusercontent.com/30685486/81926649-9d958680-9625-11ea-8e74-eb4acc194a76.png)
Maybe fields like: 
1. timetable - Course Timetable
2. homePage - Main page (a text field for people to edit to whatever they want in md format, memeesss)

**Comment by StevenShen1999** [comment]
Addressed this issue in commit 944250a, either migrate the existing database or simply recreate the database to ensure no db-related errors.
